apiVersion: v1
kind: Service
metadata:
  name: {{ include "print-log-only.fullname" . }}
  labels:
{{ include "print-log-only.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "print-log-only.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
