{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: print-log-only.kpcdevtest.kpc-dev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "name" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
