apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "routine-log.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "routine-log.name" . }}
    helm.sh/chart: {{ include "routine-log.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "routine-log.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "routine-log.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: routine-log
          image: "{{ .Values.container.repository }}:{{ .Values.container.tag }}"
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP