# Default values for print-log-only.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  repository: streamtank/print-log-only
  tag: latest
  pullPolicy: Always

initContainer: 
  repository: streamtank/print-log-init-container
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

